# type: ignore
"""init

Revision ID: ed18070009e8
Revises:
Create Date: 2025-06-24 13:31:52.992418

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "ed18070009e8"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "last_messages",
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rank_name", sa.String(), nullable=False),
        sa.Column("rank_left", sa.Integer(), nullable=False),
        sa.Column("rank_right", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("nickname"),
    )
    op.create_index(
        "ix_last_messages_points", "last_messages", ["points"], unique=False
    )
    op.create_table(
        "messages",
        sa.Column("id", sa.Integer(), autoincrement=True, nullable=False),
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rank_name", sa.String(), nullable=False),
        sa.Column("rank_left", sa.Integer(), nullable=False),
        sa.Column("rank_right", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("id"),
    )
    op.create_index(op.f("ix_messages_points"), "messages", ["points"], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f("ix_messages_points"), table_name="messages")
    op.drop_table("messages")
    op.drop_index("ix_last_messages_points", table_name="last_messages")
    op.drop_table("last_messages")
    # ### end Alembic commands ###
