# type: ignore
"""last

Revision ID: e71a4c7e1a2f
Revises: 99cec9413afe
Create Date: 2025-06-15 12:04:18.574055

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "e71a4c7e1a2f"
down_revision: str | None = "99cec9413afe"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "messages", sa.Column("id", sa.Integer(), autoincrement=True, nullable=False)
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("messages", "id")
    # ### end Alembic commands ###
