# type: ignore
"""initial

Revision ID: 4b38b36eeb0e
Revises:
Create Date: 2025-06-14 13:57:17.072834

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "4b38b36eeb0e"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "last_messages",
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rank_name", sa.String(), nullable=False),
        sa.Column("rank_left", sa.Integer(), nullable=False),
        sa.Column("rank_right", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("nickname"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("last_messages")
    # ### end Alembic commands ###
