"""initial

Revision ID: 99cec9413afe
Revises: 4b38b36eeb0e
Create Date: 2025-06-14 13:59:38.258649

"""

from collections.abc import Sequence

import sqlalchemy as sa
from alembic import op

# revision identifiers, used by Alembic.
revision: str = "99cec9413afe"
down_revision: str | None = "4b38b36eeb0e"
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table(
        "messages",
        sa.Column("nickname", sa.String(), nullable=False),
        sa.Column("date", sa.DateTime(), nullable=False),
        sa.Column("points", sa.Integer(), nullable=False),
        sa.Column("hours", sa.Float(), nullable=False),
        sa.Column("position", sa.Integer(), nullable=False),
        sa.Column("rank_name", sa.String(), nullable=False),
        sa.Column("rank_left", sa.Integer(), nullable=False),
        sa.Column("rank_right", sa.Integer(), nullable=False),
        sa.PrimaryKeyConstraint("nickname"),
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table("messages")
    # ### end Alembic commands ###
