services:
  webui:
    build:
      context: ./webui
      dockerfile: dockerfile
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm
    ports:
      - 8080:8080
    networks:
      - db_net

  collector:
    build:
      context: ./collector
      dockerfile: dockerfile
    restart: unless-stopped
    container_name: gloria_collector
    env_file:
      - ./collector/.env
    environment:
      - PYTHONUNBUFFERED=1
      - TERM=xterm
    networks:
      - db_net
      - app_net
    volumes:
      - ./collector/src/db:/app/src/db
      - ./.var/collector:/app/var/collector

  postgres:
    image: postgres:latest
    container_name: postgres_container
    environment:
      POSTGRES_USER: ${POSTGRES_USER:-user}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-123}
      POSTGRES_DB: ${POSTGRES_DB:-collector}
      PGDATA: /var/lib/postgresql/data/pgdata
    networks:
      - db_net
    volumes:
      - ./.var/pgdata:/var/lib/postgresql/data/pgdata
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    command: >
      postgres -c max_connections=1000
               -c shared_buffers=256MB
               -c effective_cache_size=768MB
               -c maintenance_work_mem=64MB
               -c checkpoint_completion_target=0.7
               -c wal_buffers=16MB
               -c default_statistics_target=100
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres_user} -d ${POSTGRES_DB:-postgres_password}"
        ]
      interval: 30s
      timeout: 10s
      retries: 5
    restart: unless-stopped
    tty: true
    stdin_open: true

  pgadmin:
    container_name: pgadmin_container
    image: dpage/pgadmin4
    environment:
      PGADMIN_DEFAULT_EMAIL: ${PGADMIN_DEFAULT_EMAIL:-pgadmin4@pgadmin.org}
      PGADMIN_DEFAULT_PASSWORD: ${PGADMIN_DEFAULT_PASSWORD:-admin}
      PGADMIN_CONFIG_SERVER_MODE: 'False'
    volumes:
      - ./.var/pgadmin:/var/lib/pgadmin
    ports:
      - "${PGADMIN_PORT:-5050}:80"
    networks:
      - db_net
      - pgadmin_net
    restart: unless-stopped

  nginx:
    image: 'jc21/nginx-proxy-manager:latest'
    container_name: nginx_npm
    restart: unless-stopped
    ports:
      - '80:80' # Public HTTP Port
      - '443:443' # Public HTTPS Port
      - '81:81' # Admin Web Port
    networks:
      - npm_db_net
      - app_net
      - pgadmin_net
    environment:
      # Postgres parameters:
      DB_POSTGRES_HOST: 'npm_db'
      DB_POSTGRES_PORT: '5432'
      DB_POSTGRES_USER: 'npm'
      DB_POSTGRES_PASSWORD: 'npmpass'
      DB_POSTGRES_NAME: 'npm'
      DISABLE_IPV6: 'true'
    volumes:
      - ./.var/data:/data
      - ./.var/letsencrypt:/etc/letsencrypt
    depends_on:
      - npm_db

  npm_db:
    image: postgres:latest
    container_name: npm_db
    restart: unless-stopped
    environment:
      POSTGRES_USER: 'npm'
      POSTGRES_PASSWORD: 'npmpass'
      POSTGRES_DB: 'npm'
    networks:
      - npm_db_net
    deploy:
      resources:
        limits:
          cpus: '0.50'
          memory: 512M
    healthcheck:
      test:
        [
          "CMD-SHELL",
          "pg_isready -U ${POSTGRES_USER:-postgres_user} -d ${POSTGRES_DB:-postgres_password}"
        ]
    volumes:
      - ./.var/npm_db:/var/lib/postgresql/data

networks:
  db_net:
  app_net:
  npm_db_net:
  pgadmin_net:


volumes:
  pgadmin:
  pgdata:
