FROM ghcr.io/astral-sh/uv:alpine

USER 1000:1000

WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1
ENV XDG_DATA_HOME=/app/data
ENV XDG_CACHE_HOME=/app/.cache/uv

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

RUN --mount=type=cache,target=/app/.cache/uv,uid=1000,gid=1000 \
  --mount=type=bind,source=uv.lock,target=uv.lock \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  uv sync --locked --no-install-project --no-dev

COPY . ./

RUN --mount=type=cache,target=/app/.cache/uv,uid=1000,gid=1000  \
  uv sync --locked --no-dev
ENV PATH="/app/.venv/bin:$PATH"

EXPOSE 8080

ENTRYPOINT []
CMD ["litestar", "run", "--host", "0.0.0.0", "--port", "8080"]
