FROM ghcr.io/astral-sh/uv:alpine

USER 1000:1000

WORKDIR /app

# Enable bytecode compilation
ENV UV_COMPILE_BYTECODE=1
ENV XDG_DATA_HOME=/app/.cache/uv/data
ENV XDG_CACHE_HOME=/app/.cache/uv

# Copy from the cache instead of linking since it's a mounted volume
ENV UV_LINK_MODE=copy

RUN --mount=type=cache,target=/home/nik/.cache/uv \
  --mount=type=bind,source=uv.lock,target=uv.lock \
  --mount=type=bind,source=pyproject.toml,target=pyproject.toml \
  uv sync --cache-dir /app/.cache/uv --locked --no-install-project --no-dev

COPY . ./

RUN --mount=type=cache,target=/home/nik/.cache/uv \
  uv sync --locked --no-dev
ENV PATH="/app/.venv/bin:$PATH"

ENTRYPOINT []
CMD [ "uv", "run", "--no-dev", "src/main.py" ]
