name: codecov
run-name: ${{ github.actor }} is testing out 🚀
on: [push, workflow_dispatch]
jobs:
  Explore-GitHub-Actions:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: cd
        run: cd collector
      - name: Install the latest version of uv
        uses: astral-sh/setup-uv@v6
      - name: run test and generate cov
        run: uv run --with pytest-cov --with pytest-asyncio pytest --cov --cov-branch --cov-report=xml
      - name: Upload coverage reports to Codecov
        uses: codecov/codecov-action@v5
        with:
          token: ${{ secrets.CODECOV_TOKEN }}
